<a href="https://colab.research.google.com/github/ykitaguchi77/ImageProcessing/blob/master/Numpy_preprocessing_for_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Numpy image processing for Pytorch**



In [23]:
import torch
import os
import IPython
import shutil
import glob
from PIL import Image
import matplotlib.pyplot as plt
import numpy as np




print('Setup complete. Using torch %s %s' % (torch.__version__, torch.cuda.get_device_properties(0) if torch.cuda.is_available() else 'CPU'))
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

#GDriveをマウント
from google.colab import drive
drive.mount('/content/drive')

Setup complete. Using torch 1.12.1+cu113 CPU
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
# image_folder = "/content/drive/MyDrive/Deep_learning/GO_extended_dataset/GO_newPatient_250px"

# img_list = glob.glob(f"{image_folder}/*")
# img = img_list[0]
# print(img)

img = "/content/drive/MyDrive/Deep_learning/Face_Images/test_dog.jpg"
# img_np = np.array(Image.open(img)).astype(np.float32)
# plt.imshow((img_np * 255).astype(np.uint8))
plt.imshow(Image.open(img))
plt.show()

In [ ]:
img = plt.imread('/content/drive/MyDrive/Deep_learning/Face_Images/test_dog.jpg')
plt.imshow(img)
plt.show()

In [44]:
def zscore(x, axis=None):
    # xmean = x.mean(axis=axis, keepdims=True)
    xmean = [0.485, 0.456, 0.406]
    # xstd = np.std(x, axis=axis, keepdims=True)
    xstd = [0.229, 0.224, 0.225]
    zscore = (x-xmean)/xstd
    return zscore

PIL_img = Image.open(img)
PIL_img = PIL_img.resize((224,224), resample=0)

#convert PIL to numpy
img_np = np.array(PIL_img).astype(np.float32)
img_np = zscore(img_np)

print(img_np)


[[[ 41.55021834  38.14285714  15.97333333]
  [ 93.95196507  91.71428571  69.30666667]
  [146.35371179 145.28571429 122.64      ]
  ...
  [355.96069869 381.89285714 304.86222222]
  [543.73362445 542.60714286 500.41777778]
  [526.26637555 538.14285714 491.52888889]]

 [[ 28.44978166  24.75         7.08444444]
  [ 72.11790393  69.39285714  51.52888889]
  [102.68558952 100.64285714  78.19555556]
  ...
  [530.63318777 529.21428571 487.08444444]
  [508.79912664 529.21428571 478.19555556]
  [513.16593886 533.67857143 482.64      ]]

 [[ 19.71615721  15.82142857  -1.80444444]
  [ 28.44978166  24.75         2.64      ]
  [ 41.55021834  38.14285714  15.97333333]
  ...
  [508.79912664 529.21428571 478.19555556]
  [517.53275109 529.21428571 482.64      ]
  [517.53275109 529.21428571 482.64      ]]

 ...

 [[587.40174672 542.60714286 620.41777778]
  [657.27074236 681.         744.86222222]
  [652.90393013 663.14285714 740.41777778]
  ...
  [377.79475983 350.64285714 340.41777778]
  [382.16157205 36

In [43]:
from torchvision import models, transforms

preprocess = transforms.Compose([
    transforms.Resize(224),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

PIL_img = Image.open(img)
img_tensor = preprocess(PIL_img)
img_np = img_tensor.to("cpu").detach().numpy().transpose(1, 2, 0).copy()
print(img_np)

[[[-1.9466565  -1.8781512  -1.7172985 ]
  [-1.8610327  -1.7906162  -1.6475817 ]
  [-1.843908   -1.7731092  -1.6127234 ]
  ...
  [-0.5081771  -0.35504198 -0.32296288]
  [-0.11430778  0.01260505  0.06047938]
  [-0.04580877  0.08263306  0.13019615]]

 [[-1.9637812  -1.8956583  -1.7347276 ]
  [-1.8781574  -1.8081232  -1.6475817 ]
  [-1.8267832  -1.7556022  -1.6127234 ]
  ...
  [-0.35405433 -0.21498597 -0.16610013]
  [-0.06293353  0.06512605  0.11276696]
  [-0.06293353  0.06512605  0.11276696]]

 [[-1.980906   -1.9131652  -1.7347276 ]
  [-1.8952821  -1.8256302  -1.68244   ]
  [-1.8267832  -1.7556022  -1.6127234 ]
  ...
  [-0.13143253 -0.02240895  0.02562099]
  [-0.08005828  0.06512605  0.09533776]
  [-0.09718303  0.06512605  0.09533776]]

 ...

 [[ 0.12543888 -0.03991595  0.47878015]
  [ 0.43368444  0.55532223  1.0539435 ]
  [ 0.5193082   0.6778712   1.193377  ]
  ...
  [-1.1246684  -1.160364   -0.9504139 ]
  [-1.004795   -1.0028011  -0.776122  ]
  [-1.1246684  -1.0903361  -0.8981263 ]]

 [